export default [
    { name: 'Afghanistan', code: '93', iso: 'AF / AFG' },
    { name: 'Albania', code: '355', iso: 'AL / ALB' },
    { name: 'Algeria', code: '213', iso: 'DZ / DZA' },
    { name: 'American Samoa', code: '1-684', iso: 'AS / ASM' },
    { name: 'Andorra', code: '376', iso: 'AD / AND' },
    { name: 'Angola', code: '244', iso: 'AO / AGO' },
    { name: 'Anguilla', code: '1-264', iso: 'AI / AIA' },
    { name: 'Antarctica', code: '672', iso: 'AQ / ATA' },
    { name: 'Antigua and Barbuda', code: '1-268', iso: 'AG / ATG' },
    { name: 'Argentina', code: '54', iso: 'AR / ARG' },
    { name: 'Armenia', code: '374', iso: 'AM / ARM' },
    { name: 'Aruba', code: '297', iso: 'AW / ABW' },
    { name: 'Australia', code: '61', iso: 'AU / AUS' },
    { name: 'Austria', code: '43', iso: 'AT / AUT' },
    { name: 'Azerbaijan', code: '994', iso: 'AZ / AZE' },
    { name: 'Bahamas', code: '1-242', iso: 'BS / BHS' },
    { name: 'Bahrain', code: '973', iso: 'BH / BHR' },
    { name: 'Bangladesh', code: '880', iso: 'BD / BGD' },
    { name: 'Barbados', code: '1-246', iso: 'BB / BRB' },
    { name: 'Belarus', code: '375', iso: 'BY / BLR' },
    { name: 'Belgium', code: '32', iso: 'BE / BEL' },
    { name: 'Belize', code: '501', iso: 'BZ / BLZ' },
    { name: 'Benin', code: '229', iso: 'BJ / BEN' },
    { name: 'Bermuda', code: '1-441', iso: 'BM / BMU' },
    { name: 'Bhutan', code: '975', iso: 'BT / BTN' },
    { name: 'Bolivia', code: '591', iso: 'BO / BOL' },
    { name: 'Bosnia and Herzegovina', code: '387', iso: 'BA / BIH' },
    { name: 'Botswana', code: '267', iso: 'BW / BWA' },
    { name: 'Brazil', code: '55', iso: 'BR / BRA' },
    { name: 'British Indian Ocean Territory', code: '246', iso: 'IO / IOT' },
    { name: 'British Virgin Islands', code: '1-284', iso: 'VG / VGB' },
    { name: 'Brunei', code: '673', iso: 'BN / BRN' },
    { name: 'Bulgaria', code: '359', iso: 'BG / BGR' },
    { name: 'Burkina Faso', code: '226', iso: 'BF / BFA' },
    { name: 'Burundi', code: '257', iso: 'BI / BDI' },
    { name: 'Cambodia', code: '855', iso: 'KH / KHM' },
    { name: 'Cameroon', code: '237', iso: 'CM / CMR' },
    { name: 'Canada', code: '1', iso: 'CA / CAN' },
    { name: 'Cape Verde', code: '238', iso: 'CV / CPV' },
    { name: 'Cayman Islands', code: '1-345', iso: 'KY / CYM' },
    { name: 'Central African Republic', code: '236', iso: 'CF / CAF' },
    { name: 'Chad', code: '235', iso: 'TD / TCD' },
    { name: 'Chile', code: '56', iso: 'CL / CHL' },
    { name: 'China', code: '86', iso: 'CN / CHN' },
    { name: 'Christmas Island', code: '61', iso: 'CX / CXR' },
    { name: 'Cocos Islands', code: '61', iso: 'CC / CCK' },
    { name: 'Colombia', code: '57', iso: 'CO / COL' },
    { name: 'Comoros', code: '269', iso: 'KM / COM' },
    { name: 'Cook Islands', code: '682', iso: 'CK / COK' },
    { name: 'Costa Rica', code: '506', iso: 'CR / CRI' },
    { name: 'Croatia', code: '385', iso: 'HR / HRV' },
    { name: 'Cuba', code: '53', iso: 'CU / CUB' },
    { name: 'Curacao', code: '599', iso: 'CW / CUW' },
    { name: 'Cyprus', code: '357', iso: 'CY / CYP' },
    { name: 'Czech Republic', code: '420', iso: 'CZ / CZE' },
    { name: 'Democratic Republic of the Congo', code: '243', iso: 'CD / COD' },
    { name: 'Denmark', code: '45', iso: 'DK / DNK' },
    { name: 'Djibouti', code: '253', iso: 'DJ / DJI' },
    { name: 'Dominica', code: '1-767', iso: 'DM / DMA' },
    { name: 'Dominican Republic', code: '1-809, 1-829, 1-849', iso: 'DO / DOM' },
    { name: 'East Timor', code: '670', iso: 'TL / TLS' },
    { name: 'Ecuador', code: '593', iso: 'EC / ECU' },
    { name: 'Egypt', code: '20', iso: 'EG / EGY' },
    { name: 'El Salvador', code: '503', iso: 'SV / SLV' },
    { name: 'Equatorial Guinea', code: '240', iso: 'GQ / GNQ' },
    { name: 'Eritrea', code: '291', iso: 'ER / ERI' },
    { name: 'Estonia', code: '372', iso: 'EE / EST' },
    { name: 'Ethiopia', code: '251', iso: 'ET / ETH' },
    { name: 'Falkland Islands', code: '500', iso: 'FK / FLK' },
    { name: 'Faroe Islands', code: '298', iso: 'FO / FRO' },
    { name: 'Fiji', code: '679', iso: 'FJ / FJI' },
    { name: 'Finland', code: '358', iso: 'FI / FIN' },
    { name: 'France', code: '33', iso: 'FR / FRA' },
    { name: 'French Polynesia', code: '689', iso: 'PF / PYF' },
    { name: 'Gabon', code: '241', iso: 'GA / GAB' },
    { name: 'Gambia', code: '220', iso: 'GM / GMB' },
    { name: 'Georgia', code: '995', iso: 'GE / GEO' },
    { name: 'Germany', code: '49', iso: 'DE / DEU' },
    { name: 'Ghana', code: '233', iso: 'GH / GHA' },
    { name: 'Gibraltar', code: '350', iso: 'GI / GIB' },
    { name: 'Greece', code: '30', iso: 'GR / GRC' },
    { name: 'Greenland', code: '299', iso: 'GL / GRL' },
    { name: 'Grenada', code: '1-473', iso: 'GD / GRD' },
    { name: 'Guam', code: '1-671', iso: 'GU / GUM' },
    { name: 'Guatemala', code: '502', iso: 'GT / GTM' },
    { name: 'Guernsey', code: '44-1481', iso: 'GG / GGY' },
    { name: 'Guinea', code: '224', iso: 'GN / GIN' },
    { name: 'Guinea-Bissau', code: '245', iso: 'GW / GNB' },
    { name: 'Guyana', code: '592', iso: 'GY / GUY' },
    { name: 'Haiti', code: '509', iso: 'HT / HTI' },
    { name: 'Honduras', code: '504', iso: 'HN / HND' },
    { name: 'Hong Kong', code: '852', iso: 'HK / HKG' },
    { name: 'Hungary', code: '36', iso: 'HU / HUN' },
    { name: 'Iceland', code: '354', iso: 'IS / ISL' },
    { name: 'India', code: '91', iso: 'IN / IND' },
    { name: 'Indonesia', code: '62', iso: 'ID / IDN' },
    { name: 'Iran', code: '98', iso: 'IR / IRN' },
    { name: 'Iraq', code: '964', iso: 'IQ / IRQ' },
    { name: 'Ireland', code: '353', iso: 'IE / IRL' },
    { name: 'Isle of Man', code: '44-1624', iso: 'IM / IMN' },
    { name: 'Israel', code: '972', iso: 'IL / ISR' },
    { name: 'Italy', code: '39', iso: 'IT / ITA' },
    { name: 'Ivory Coast', code: '225', iso: 'CI / CIV' },
    { name: 'Jamaica', code: '1-876', iso: 'JM / JAM' },
    { name: 'Japan', code: '81', iso: 'JP / JPN' },
    { name: 'Jersey', code: '44-1534', iso: 'JE / JEY' },
    { name: 'Jordan', code: '962', iso: 'JO / JOR' },
    { name: 'Kazakhstan', code: '7', iso: 'KZ / KAZ' },
    { name: 'Kenya', code: '254', iso: 'KE / KEN' },
    { name: 'Kiribati', code: '686', iso: 'KI / KIR' },
    { name: 'Kosovo', code: '383', iso: 'XK / XKX' },
    { name: 'Kuwait', code: '965', iso: 'KW / KWT' },
    { name: 'Kyrgyzstan', code: '996', iso: 'KG / KGZ' },
    { name: 'Laos', code: '856', iso: 'LA / LAO' },
    { name: 'Latvia', code: '371', iso: 'LV / LVA' },
    { name: 'Lebanon', code: '961', iso: 'LB / LBN' },
    { name: 'Lesotho', code: '266', iso: 'LS / LSO' },
    { name: 'Liberia', code: '231', iso: 'LR / LBR' },
    { name: 'Libya', code: '218', iso: 'LY / LBY' },
    { name: 'Liechtenstein', code: '423', iso: 'LI / LIE' },
    { name: 'Lithuania', code: '370', iso: 'LT / LTU' },
    { name: 'Luxembourg', code: '352', iso: 'LU / LUX' },
    { name: 'Macau', code: '853', iso: 'MO / MAC' },
    { name: 'Macedonia', code: '389', iso: 'MK / MKD' },
    { name: 'Madagascar', code: '261', iso: 'MG / MDG' },
    { name: 'Malawi', code: '265', iso: 'MW / MWI' },
    { name: 'Malaysia', code: '60', iso: 'MY / MYS' },
    { name: 'Maldives', code: '960', iso: 'MV / MDV' },
    { name: 'Mali', code: '223', iso: 'ML / MLI' },
    { name: 'Malta', code: '356', iso: 'MT / MLT' },
    { name: 'Marshall Islands', code: '692', iso: 'MH / MHL' },
    { name: 'Mauritania', code: '222', iso: 'MR / MRT' },
    { name: 'Mauritius', code: '230', iso: 'MU / MUS' },
    { name: 'Mayotte', code: '262', iso: 'YT / MYT' },
    { name: 'Mexico', code: '52', iso: 'MX / MEX' },
    { name: 'Micronesia', code: '691', iso: 'FM / FSM' },
    { name: 'Moldova', code: '373', iso: 'MD / MDA' },
    { name: 'Monaco', code: '377', iso: 'MC / MCO' },
    { name: 'Mongolia', code: '976', iso: 'MN / MNG' },
    { name: 'Montenegro', code: '382', iso: 'ME / MNE' },
    { name: 'Montserrat', code: '1-664', iso: 'MS / MSR' },
    { name: 'Morocco', code: '212', iso: 'MA / MAR' },
    { name: 'Mozambique', code: '258', iso: 'MZ / MOZ' },
    { name: 'Myanmar', code: '95', iso: 'MM / MMR' },
    { name: 'Namibia', code: '264', iso: 'NA / NAM' },
    { name: 'Nauru', code: '674', iso: 'NR / NRU' },
    { name: 'Nepal', code: '977', iso: 'NP / NPL' },
    { name: 'Netherlands', code: '31', iso: 'NL / NLD' },
    { name: 'Netherlands Antilles', code: '599', iso: 'AN / ANT' },
    { name: 'New Caledonia', code: '687', iso: 'NC / NCL' },
    { name: 'New Zealand', code: '64', iso: 'NZ / NZL' },
    { name: 'Nicaragua', code: '505', iso: 'NI / NIC' },
    { name: 'Niger', code: '227', iso: 'NE / NER' },
    { name: 'Nigeria', code: '234', iso: 'NG / NGA' },
    { name: 'Niue', code: '683', iso: 'NU / NIU' },
    { name: 'North Korea', code: '850', iso: 'KP / PRK' },
    { name: 'Northern Mariana Islands', code: '1-670', iso: 'MP / MNP' },
    { name: 'Norway', code: '47', iso: 'NO / NOR' },
    { name: 'Oman', code: '968', iso: 'OM / OMN' },
    { name: 'Pakistan', code: '92', iso: 'PK / PAK' },
    { name: 'Palau', code: '680', iso: 'PW / PLW' },
    { name: 'Palestine', code: '970', iso: 'PS / PSE' },
    { name: 'Panama', code: '507', iso: 'PA / PAN' },
    { name: 'Papua New Guinea', code: '675', iso: 'PG / PNG' },
    { name: 'Paraguay', code: '595', iso: 'PY / PRY' },
    { name: 'Peru', code: '51', iso: 'PE / PER' },
    { name: 'Philippines', code: '63', iso: 'PH / PHL' },
    { name: 'Pitcairn', code: '64', iso: 'PN / PCN' },
    { name: 'Poland', code: '48', iso: 'PL / POL' },
    { name: 'Portugal', code: '351', iso: 'PT / PRT' },
    { name: 'Puerto Rico', code: '1-787, 1-939', iso: 'PR / PRI' },
    { name: 'Qatar', code: '974', iso: 'QA / QAT' },
    { name: 'Republic of the Congo', code: '242', iso: 'CG / COG' },
    { name: 'Reunion', code: '262', iso: 'RE / REU' },
    { name: 'Romania', code: '40', iso: 'RO / ROU' },
    { name: 'Russia', code: '7', iso: 'RU / RUS' },
    { name: 'Rwanda', code: '250', iso: 'RW / RWA' },
    { name: 'Saint Barthelemy', code: '590', iso: 'BL / BLM' },
    { name: 'Saint Helena', code: '290', iso: 'SH / SHN' },
    { name: 'Saint Kitts and Nevis', code: '1-869', iso: 'KN / KNA' },
    { name: 'Saint Lucia', code: '1-758', iso: 'LC / LCA' },
    { name: 'Saint Martin', code: '590', iso: 'MF / MAF' },
    { name: 'Saint Pierre and Miquelon', code: '508', iso: 'PM / SPM' },
    { name: 'Saint Vincent and the Grenadines', code: '1-784', iso: 'VC / VCT' },
    { name: 'Samoa', code: '685', iso: 'WS / WSM' },
    { name: 'San Marino', code: '378', iso: 'SM / SMR' },
    { name: 'Sao Tome and Principe', code: '239', iso: 'ST / STP' },
    { name: 'Saudi Arabia', code: '966', iso: 'SA / SAU' },
    { name: 'Senegal', code: '221', iso: 'SN / SEN' },
    { name: 'Serbia', code: '381', iso: 'RS / SRB' },
    { name: 'Seychelles', code: '248', iso: 'SC / SYC' },
    { name: 'Sierra Leone', code: '232', iso: 'SL / SLE' },
    { name: 'Singapore', code: '65', iso: 'SG / SGP' },
    { name: 'Sint Maarten', code: '1-721', iso: 'SX / SXM' },
    { name: 'Slovakia', code: '421', iso: 'SK / SVK' },
    { name: 'Slovenia', code: '386', iso: 'SI / SVN' },
    { name: 'Solomon Islands', code: '677', iso: 'SB / SLB' },
    { name: 'Somalia', code: '252', iso: 'SO / SOM' },
    { name: 'South Africa', code: '27', iso: 'ZA / ZAF' },
    { name: 'South Korea', code: '82', iso: 'KR / KOR' },
    { name: 'South Sudan', code: '211', iso: 'SS / SSD' },
    { name: 'Spain', code: '34', iso: 'ES / ESP' },
    { name: 'Sri Lanka', code: '94', iso: 'LK / LKA' },
    { name: 'Sudan', code: '249', iso: 'SD / SDN' },
    { name: 'Suriname', code: '597', iso: 'SR / SUR' },
    { name: 'Svalbard and Jan Mayen', code: '47', iso: 'SJ / SJM' },
    { name: 'Swaziland', code: '268', iso: 'SZ / SWZ' },
    { name: 'Sweden', code: '46', iso: 'SE / SWE' },
    { name: 'Switzerland', code: '41', iso: 'CH / CHE' },
    { name: 'Syria', code: '963', iso: 'SY / SYR' },
    { name: 'Taiwan', code: '886', iso: 'TW / TWN' },
    { name: 'Tajikistan', code: '992', iso: 'TJ / TJK' },
    { name: 'Tanzania', code: '255', iso: 'TZ / TZA' },
    { name: 'Thailand', code: '66', iso: 'TH / THA' },
    { name: 'Togo', code: '228', iso: 'TG / TGO' },
    { name: 'Tokelau', code: '690', iso: 'TK / TKL' },
    { name: 'Tonga', code: '676', iso: 'TO / TON' },
    { name: 'Trinidad and Tobago', code: '1-868', iso: 'TT / TTO' },
    { name: 'Tunisia', code: '216', iso: 'TN / TUN' },
    { name: 'Turkey', code: '90', iso: 'TR / TUR' },
    { name: 'Turkmenistan', code: '993', iso: 'TM / TKM' },
    { name: 'Turks and Caicos Islands', code: '1-649', iso: 'TC / TCA' },
    { name: 'Tuvalu', code: '688', iso: 'TV / TUV' },
    { name: 'U.S. Virgin Islands', code: '1-340', iso: 'VI / VIR' },
    { name: 'Uganda', code: '256', iso: 'UG / UGA' },
    { name: 'Ukraine', code: '380', iso: 'UA / UKR' },
    { name: 'United Arab Emirates', code: '971', iso: 'AE / ARE' },
    { name: 'United Kingdom', code: '44', iso: 'GB / GBR' },
    { name: 'United States', code: '1', iso: 'US / USA' },
    { name: 'Uruguay', code: '598', iso: 'UY / URY' },
    { name: 'Uzbekistan', code: '998', iso: 'UZ / UZB' },
    { name: 'Vanuatu', code: '678', iso: 'VU / VUT' },
    { name: 'Vatican', code: '379', iso: 'VA / VAT' },
    { name: 'Venezuela', code: '58', iso: 'VE / VEN' },
    { name: 'Vietnam', code: '84', iso: 'VN / VNM' },
    { name: 'Wallis and Futuna', code: '681', iso: 'WF / WLF' },
    { name: 'Western Sahara', code: '212', iso: 'EH / ESH' },
    { name: 'Yemen', code: '967', iso: 'YE / YEM' },
    { name: 'Zambia', code: '260', iso: 'ZM / ZMB' },
    { name: 'Zimbabwe', code: '263', iso: 'ZW / ZWE' },
]